/**
 * Mock Data cho Academic Affairs Module
 * Chứa dữ liệu mẫu chi tiết cho tất cả tính năng
 */

// ===== 1. PENDING APPROVALS =====
export const pendingApprovalsData = [
  {
    id: "ap_001",
    name: "Cơ Sở Dữ Liệu",
    code: "CS101",
    teacher: "Lê Văn C",
    department: "Khoa CNTT",
    date: "03/01/2026",
    status: "pending_approval",
    credits: 3,
    semester: "Học kỳ 1",
  },
  {
    id: "ap_002",
    name: "Lập Trình Web",
    code: "CS102",
    teacher: "Trần Thị B",
    department: "Khoa CNTT",
    date: "02/01/2026",
    status: "pending_approval",
    credits: 3,
    semester: "Học kỳ 1",
  },
  {
    id: "ap_003",
    name: "Toán Cao Cấp",
    code: "MAT101",
    teacher: "Nguyễn Văn A",
    department: "Khoa Toán",
    date: "01/01/2026",
    status: "pending_approval",
    credits: 4,
    semester: "Học kỳ 1",
  },
  {
    id: "ap_004",
    name: "Mạng Máy Tính",
    code: "CS103",
    teacher: "Phạm Anh T",
    department: "Khoa CNTT",
    date: "31/12/2025",
    status: "pending_approval",
    credits: 3,
    semester: "Học kỳ 2",
  },
  {
    id: "ap_005",
    name: "Công Nghệ Phần Mềm",
    code: "CS104",
    teacher: "Hoàng Minh K",
    department: "Khoa CNTT",
    date: "30/12/2025",
    status: "pending_approval",
    credits: 3,
    semester: "Học kỳ 1",
  },
];

// ===== 2. PLO MASTER DATA =====
export const ploMasterData = {
  PLO1: {
    code: "PLO1",
    title: "Kiến thức cơ bản về lĩnh vực",
    group: "Knowledge",
    category: "knowledge",
    description:
      "Người học nắm được nền tảng kiến thức cốt lõi của ngành/chuyên ngành, hiểu khái niệm và nguyên lý cơ bản.",
    keywords: ["khái niệm", "lý thuyết", "cơ bản", "nguyên lý", "kiến thức", "nền tảng"],
    status: "active",
    updatedAt: "2026-01-22",
  },
  PLO2: {
    code: "PLO2",
    title: "Kỹ năng thực hành chuyên môn",
    group: "Skills",
    category: "skills",
    description:
      "Người học áp dụng được kiến thức vào giải quyết bài toán thực tế, thực hiện thao tác chuyên môn và quy trình làm việc.",
    keywords: ["áp dụng", "thực hành", "thiết kế", "triển khai", "xây dựng", "lập trình", "giải quyết", "quy trình"],
    status: "active",
    updatedAt: "2026-01-22",
  },
  PLO3: {
    code: "PLO3",
    title: "Thái độ nghề nghiệp và đạo đức",
    group: "Attitude",
    category: "attitude",
    description:
      "Người học thể hiện trách nhiệm nghề nghiệp, tuân thủ đạo đức, làm việc nhóm và giao tiếp hiệu quả trong môi trường học thuật.",
    keywords: ["đạo đức", "trách nhiệm", "thái độ", "tuân thủ", "kỷ luật", "làm việc nhóm", "giao tiếp"],
    status: "active",
    updatedAt: "2026-01-22",
  },
  PLO4: {
    code: "PLO4",
    title: "Kỹ năng quản lý và lãnh đạo",
    group: "Leadership",
    category: "skills",
    description:
      "Người học có khả năng quản lý dự án, lãnh đạo nhóm, ra quyết định và xử lý tình huống phức tạp.",
    keywords: ["quản lý", "lãnh đạo", "quyết định", "lập kế hoạch", "tổ chức", "điều phối"],
    status: "active",
    updatedAt: "2026-01-22",
  },
};

// ===== 3. CLO/PLO MAPPING (PLO CHECK DATA) =====
export const ploCheckMappingData = [
  {
    id: "map_001",
    subject: "Lập trình Web",
    code: "CS102",
    lecturer: "ThS. Nguyễn Văn A",
    submittedAt: "2024-01-15",
    clo: "CLO1: Hiểu khái niệm lập trình web cơ bản",
    plo: "PLO1: Kiến thức cơ bản",
    status: { label: "Phù hợp", tone: "ok" },
    note: "",
    lastReviewedAt: null,
  },
  {
    id: "map_002",
    subject: "Công nghệ phần mềm",
    code: "CS104",
    lecturer: "TS. Trần Thị B",
    submittedAt: "2024-01-18",
    clo: "CLO2: Áp dụng quy trình phát triển phần mềm",
    plo: "PLO2: Kỹ năng thực hành",
    status: { label: "Cần điều chỉnh", tone: "warn" },
    note: "CLO mô tả chung, cần gắn rubric/đánh giá rõ hơn.",
    lastReviewedAt: null,
  },
  {
    id: "map_003",
    subject: "Đạo đức nghề nghiệp",
    code: "ETH101",
    lecturer: "PGS. Phạm Văn C",
    submittedAt: "2024-01-20",
    clo: "CLO3: Thực hành tuân thủ đạo đức",
    plo: "PLO3: Thái độ chuyên môn",
    status: { label: "Phù hợp", tone: "ok" },
    note: "",
    lastReviewedAt: "2024-01-25",
  },
  {
    id: "map_004",
    subject: "Cơ sở dữ liệu",
    code: "CS101",
    lecturer: "TS. Lê Minh K",
    submittedAt: "2024-01-22",
    clo: "CLO4: Thiết kế schema cơ sở dữ liệu",
    plo: "PLO2: Kỹ năng thực hành",
    status: { label: "Phù hợp", tone: "ok" },
    note: "",
    lastReviewedAt: "2024-01-28",
  },
  {
    id: "map_005",
    subject: "Quản lý dự án",
    code: "PM101",
    lecturer: "TS. Hoàng Văn D",
    submittedAt: "2024-01-25",
    clo: "CLO5: Lập kế hoạch và quản lý dự án",
    plo: "PLO4: Kỹ năng quản lý",
    status: { label: "Không phù hợp", tone: "bad" },
    note: "CLO không rõ ràng, thiếu chỉ tiêu đo lường cụ thể.",
    lastReviewedAt: null,
  },
  {
    id: "map_006",
    subject: "Toán Cao Cấp",
    code: "MAT101",
    lecturer: "PGS. Trần Hữu T",
    submittedAt: "2024-01-26",
    clo: "CLO6: Nắm vững các định lý toán học cơ bản",
    plo: "PLO1: Kiến thức cơ bản",
    status: { label: "Phù hợp", tone: "ok" },
    note: "",
    lastReviewedAt: "2024-02-01",
  },
];

// ===== 4. APPROVAL RESULTS =====
export const approvalResultsData = [
  {
    id: "ar_001",
    subject: "Lập trình Web",
    code: "CS102",
    creator: "Nguyễn Văn Chiến",
    department: "Khoa CNTT",
    result: "approved",
    approvedAt: "05/01/2026",
    approvedBy: "Trần Thị Hương",
  },
  {
    id: "ar_002",
    subject: "Công nghệ phần mềm",
    code: "CS104",
    creator: "Trần Thị B",
    department: "Khoa CNTT",
    result: "rejected",
    approvedAt: "04/01/2026",
    approvedBy: "Phạm Văn Hùng",
    reason: "CLO không cụ thể, cần chỉnh sửa lại",
  },
  {
    id: "ar_003",
    subject: "Cơ sở dữ liệu",
    code: "CS101",
    creator: "Lê Minh K",
    department: "Khoa CNTT",
    result: "approved",
    approvedAt: "03/01/2026",
    approvedBy: "Trần Thị Hương",
  },
  {
    id: "ar_004",
    subject: "Toán Cao Cấp",
    code: "MAT101",
    creator: "Nguyễn Văn A",
    department: "Khoa Toán",
    result: "approved",
    approvedAt: "02/01/2026",
    approvedBy: "Phạm Văn Hùng",
  },
  {
    id: "ar_005",
    subject: "Mạng Máy Tính",
    code: "CS103",
    creator: "Phạm Anh T",
    department: "Khoa CNTT",
    result: "rejected",
    approvedAt: "01/01/2026",
    approvedBy: "Trần Thị Hương",
    reason: "Nội dung chưa được cập nhật theo tiêu chuẩn mới",
  },
];

// ===== 5. CURRICULUM PROGRAMS =====
export const curriculumProgramsData = [
  {
    id: 1,
    name: "Công Nghệ Thông Tin",
    code: "CNTT",
    description: "Đào tạo lập trình viên chuyên nghiệp",
    credits: 120,
    courses: [
      "Lập trình Web",
      "Cơ sở dữ liệu",
      "Công nghệ phần mềm",
      "Mạng máy tính",
      "Lập trình C++",
      "Hệ điều hành",
    ],
    startYear: 2023,
    updatedAt: "2026-01-15",
  },
  {
    id: 2,
    name: "Kế Toán - Tài Chính",
    code: "KT",
    description: "Đào tạo kế toán viên chuyên nghiệp",
    credits: 120,
    courses: [
      "Kế toán tài chính",
      "Luật thuế",
      "Kiểm toán",
      "Phân tích tài chính",
      "Kế toán quản trị",
    ],
    startYear: 2023,
    updatedAt: "2026-01-10",
  },
  {
    id: 3,
    name: "Quản Lý Kinh Doanh",
    code: "QLKD",
    description: "Đào tạo nhà quản lý kinh doanh hiện đại",
    credits: 120,
    courses: [
      "Chiến lược kinh doanh",
      "Quản lý nhân sự",
      "Quản lý tài chính",
      "Tiếp thị chiến lược",
      "Quản lý hoạt động",
    ],
    startYear: 2024,
    updatedAt: "2026-01-12",
  },
  {
    id: 4,
    name: "Luật Học",
    code: "L",
    description: "Đào tạo luật sư chuyên nghiệp",
    credits: 120,
    courses: [
      "Luật hình sự",
      "Luật dân sự",
      "Luật thương mại",
      "Luật lao động",
      "Luật quốc tế",
    ],
    startYear: 2023,
    updatedAt: "2026-01-08",
  },
  {
    id: 5,
    name: "Sư Phạm - Giáo Dục",
    code: "GD",
    description: "Đào tạo giáo viên ngoài",
    credits: 120,
    courses: [
      "Phương pháp giảng dạy",
      "Tâm lý giáo dục",
      "Quản lý lớp học",
      "Đánh giá học tập",
      "Công nghệ giáo dục",
    ],
    startYear: 2024,
    updatedAt: "2026-01-18",
  },
  {
    id: 6,
    name: "Y Học - Điều Dưỡng",
    code: "YT",
    description: "Đào tạo y sĩ và điều dưỡng",
    credits: 120,
    courses: [
      "Giải phẫu học",
      "Sinh lý học",
      "Bệnh học",
      "Kỹ năng điều dưỡng",
      "Y tế công cộng",
    ],
    startYear: 2023,
    updatedAt: "2026-01-14",
  },
  {
    id: 7,
    name: "Kỹ Thuật Xây Dựng",
    code: "KTXD",
    description: "Đào tạo kỹ sư xây dựng",
    credits: 120,
    courses: [
      "Thiết kế kết cấu",
      "Vật liệu xây dựng",
      "Quản lý công trình",
      "An toàn lao động",
      "Cơ học kỹ thuật",
    ],
    startYear: 2024,
    updatedAt: "2026-01-20",
  },
  {
    id: 8,
    name: "Ngoại Ngữ - Tiếng Anh",
    code: "EN",
    description: "Đào tạo giáo viên tiếng Anh chuyên nghiệp",
    credits: 120,
    courses: [
      "Ngữ pháp tiếng Anh",
      "Kỹ năng giao tiếp",
      "Văn học Anh Mỹ",
      "Phương pháp dạy tiếng Anh",
    ],
    startYear: 2024,
    updatedAt: "2026-01-19",
  },
];

// ===== 6. LOOKUP BY SEMESTER =====
export const lookupBySemesterData = [
  {
    id: "sy_001",
    year: "2025-2026",
    semester: "Học kỳ 1",
    subject: "Lập trình Web",
    code: "CS102",
    teacher: "Nguyễn Văn Chiến",
    status: "approved",
    updatedAt: "05/01/2026",
    credits: 3,
    department: "Khoa CNTT",
  },
  {
    id: "sy_002",
    year: "2025-2026",
    semester: "Học kỳ 1",
    subject: "Công nghệ phần mềm",
    code: "CS104",
    teacher: "Trần Thị B",
    status: "approved",
    updatedAt: "04/01/2026",
    credits: 3,
    department: "Khoa CNTT",
  },
  {
    id: "sy_003",
    year: "2025-2026",
    semester: "Học kỳ 1",
    subject: "Cơ sở dữ liệu",
    code: "CS101",
    teacher: "Lê Minh K",
    status: "pending",
    updatedAt: "03/01/2026",
    credits: 3,
    department: "Khoa CNTT",
  },
  {
    id: "sy_004",
    year: "2025-2026",
    semester: "Học kỳ 1",
    subject: "Mạng máy tính",
    code: "CS103",
    teacher: "Phạm Anh T",
    status: "rejected",
    updatedAt: "02/01/2026",
    credits: 3,
    department: "Khoa CNTT",
  },
  {
    id: "sy_005",
    year: "2024-2025",
    semester: "Học kỳ 2",
    subject: "Lập trình Web",
    code: "CS102",
    teacher: "Nguyễn Văn Chiến",
    status: "approved",
    updatedAt: "10/06/2025",
    credits: 3,
    department: "Khoa CNTT",
  },
  {
    id: "sy_006",
    year: "2025-2026",
    semester: "Học kỳ 1",
    subject: "Toán Cao Cấp",
    code: "MAT101",
    teacher: "Nguyễn Văn A",
    status: "approved",
    updatedAt: "01/01/2026",
    credits: 4,
    department: "Khoa Toán",
  },
  {
    id: "sy_007",
    year: "2025-2026",
    semester: "Học kỳ 2",
    subject: "Cơ sở dữ liệu nâng cao",
    code: "CS201",
    teacher: "Lê Minh K",
    status: "approved",
    updatedAt: "18/12/2025",
    credits: 3,
    department: "Khoa CNTT",
  },
  {
    id: "sy_008",
    year: "2024-2025",
    semester: "Học kỳ 1",
    subject: "Lập trình C++",
    code: "CS105",
    teacher: "Hoàng Minh K",
    status: "approved",
    updatedAt: "15/09/2025",
    credits: 3,
    department: "Khoa CNTT",
  },
];

// ===== 7. COMPARE SYLLABUS =====
export const compareSyllabusData = [
  {
    id: "web_2025_hk1",
    label: "Lập trình Web • HK1 2025",
    meta: {
      subject: "Lập trình Web",
      code: "CS102",
      year: "2025-2026",
      semester: "Học kỳ 1",
      teacher: "Nguyễn Văn Chiến",
      updatedAt: "05/01/2026",
    },
    sections: {
      "Mục tiêu học tập": "Hiểu khái niệm cơ bản lập trình web, HTML, CSS, JavaScript",
      "Nội dung": "5 chương: Web Basics, HTML, CSS, JavaScript, DOM",
      "CLO":
        "CLO1: Hiểu khái niệm\nCLO2: Viết mã HTML/CSS\nCLO3: Lập trình JavaScript",
      "Đánh giá": "Bài tập 30% • Thi 70%",
      "Tài liệu": "Giáo trình A, Tài liệu web MDN",
      "Yêu cầu": "Những kiến thức CSS cơ bản",
    },
  },
  {
    id: "web_2024_hk1",
    label: "Lập trình Web • HK1 2024",
    meta: {
      subject: "Lập trình Web",
      code: "CS102",
      year: "2024-2025",
      semester: "Học kỳ 1",
      teacher: "Nguyễn Văn Chiến",
      updatedAt: "06/01/2025",
    },
    sections: {
      "Mục tiêu học tập": "Hiểu khái niệm và áp dụng lập trình web",
      "Nội dung": "6 chương: Web Basics, HTML, CSS, JavaScript, API, Database",
      "CLO":
        "CLO1: Hiểu khái niệm\nCLO2: Viết mã HTML/CSS\nCLO3: Lập trình JavaScript\nCLO4: Sử dụng API",
      "Đánh giá": "Bài tập 40% • Thi 60%",
      "Tài liệu": "Giáo trình A + tài liệu bổ sung B",
      "Yêu cầu": "Kiến thức lập trình cơ bản, HTML",
    },
  },
  {
    id: "cnpm_2025_hk1",
    label: "Công nghệ phần mềm • HK1 2025",
    meta: {
      subject: "Công nghệ phần mềm",
      code: "CS104",
      year: "2025-2026",
      semester: "Học kỳ 1",
      teacher: "Trần Thị B",
      updatedAt: "04/01/2026",
    },
    sections: {
      "Mục tiêu học tập": "Nắm vững quy trình phát triển phần mềm",
      "Nội dung": "8 chương: Processes, Requirements, Design, Testing, Maintenance",
      "CLO":
        "CLO1: Hiểu quy trình\nCLO2: Áp dụng trong dự án\nCLO3: Thiết kế kiến trúc",
      "Đánh giá": "Project 50% • Thi 50%",
      "Tài liệu": "Giáo trình B, Sommerville",
      "Yêu cầu": "Kinh nghiệm lập trình, hiểu cơ sở dữ liệu",
    },
  },
  {
    id: "data_2025_hk1",
    label: "Cơ sở dữ liệu • HK1 2025",
    meta: {
      subject: "Cơ sở dữ liệu",
      code: "CS101",
      year: "2025-2026",
      semester: "Học kỳ 1",
      teacher: "Lê Minh K",
      updatedAt: "03/01/2026",
    },
    sections: {
      "Mục tiêu học tập": "Hiểu mô hình dữ liệu quan hệ và SQL",
      "Nội dung": "7 chương: Data Models, SQL, Indexes, Transactions, NoSQL",
      "CLO":
        "CLO1: Thiết kế schema\nCLO2: Viết query SQL\nCLO3: Tối ưu hiệu năng",
      "Đánh giá": "Bài tập 35% • Bài thi giữa kỳ 30% • Bài thi cuối kỳ 35%",
      "Tài liệu": "Giáo trình C, Database Design Guide",
      "Yêu cầu": "Cấu trúc dữ liệu cơ bản",
    },
  },
  {
    id: "data_2024_hk2",
    label: "Cơ sở dữ liệu • HK2 2024",
    meta: {
      subject: "Cơ sở dữ liệu",
      code: "CS101",
      year: "2024-2025",
      semester: "Học kỳ 2",
      teacher: "Lê Minh K",
      updatedAt: "20/06/2025",
    },
    sections: {
      "Mục tiêu học tập": "Hiểu mô hình dữ liệu quan hệ",
      "Nội dung": "5 chương: Data Models, SQL, Indexes, Transactions",
      "CLO": "CLO1: Thiết kế schema\nCLO2: Viết query SQL",
      "Đánh giá": "Bài tập 40% • Thi 60%",
      "Tài liệu": "Giáo trình C",
      "Yêu cầu": "Lập trình cơ bản",
    },
  },
];

// ===== 8. STATISTICS & SUMMARY =====
export const statisticsData = {
  pending: {
    total: 15,
    byDepartment: {
      "Khoa CNTT": 8,
      "Khoa Toán": 3,
      "Khoa Kinh Tế": 2,
      "Khoa Luật": 2,
    },
  },
  approved: {
    total: 42,
    thisMonth: 12,
  },
  rejected: {
    total: 8,
    thisMonth: 2,
  },
  courses: {
    total: 156,
    active: 148,
    archived: 8,
  },
};

// ===== 9. FACULTIES & DEPARTMENTS =====
export const facultiesData = [
  {
    id: "fac_001",
    code: "CNTT",
    name: "Khoa Công Nghệ Thông Tin",
    dean: "TS. Trần Văn Hùng",
    email: "tran.van.hung@university.edu.vn",
    phone: "0912345678",
    syllabusCount: 28,
  },
  {
    id: "fac_002",
    code: "TOAN",
    name: "Khoa Toán - Thống Kê",
    dean: "PGS.TS. Nguyễn Thị Thu",
    email: "nguyen.thi.thu@university.edu.vn",
    phone: "0912345679",
    syllabusCount: 15,
  },
  {
    id: "fac_003",
    code: "KT",
    name: "Khoa Kế Toán - Tài Chính",
    dean: "TS. Lê Anh Tuấn",
    email: "le.anh.tuan@university.edu.vn",
    phone: "0912345680",
    syllabusCount: 22,
  },
  {
    id: "fac_004",
    code: "LUAТ",
    name: "Khoa Luật",
    dean: "PGS. Phạm Anh Tuyên",
    email: "pham.anh.tuyen@university.edu.vn",
    phone: "0912345681",
    syllabusCount: 18,
  },
];

// ===== 10. LECTURERS =====
export const lecturersData = [
  {
    id: "lec_001",
    name: "Nguyễn Văn Chiến",
    code: "NVC001",
    degree: "ThS",
    faculty: "Khoa CNTT",
    email: "nguyen.van.chien@university.edu.vn",
    syllabusCount: 3,
    status: "active",
  },
  {
    id: "lec_002",
    name: "Trần Thị B",
    code: "TTB001",
    degree: "TS",
    faculty: "Khoa CNTT",
    email: "tran.thi.b@university.edu.vn",
    syllabusCount: 2,
    status: "active",
  },
  {
    id: "lec_003",
    name: "Lê Minh K",
    code: "LMK001",
    degree: "TS",
    faculty: "Khoa CNTT",
    email: "le.minh.k@university.edu.vn",
    syllabusCount: 4,
    status: "active",
  },
  {
    id: "lec_004",
    name: "Nguyễn Văn A",
    code: "NVA001",
    degree: "PGS",
    faculty: "Khoa Toán",
    email: "nguyen.van.a@university.edu.vn",
    syllabusCount: 2,
    status: "active",
  },
  {
    id: "lec_005",
    name: "Phạm Anh T",
    code: "PAT001",
    degree: "TS",
    faculty: "Khoa CNTT",
    email: "pham.anh.t@university.edu.vn",
    syllabusCount: 1,
    status: "active",
  },
];
